language: go

install:
  - go get github.com/mattn/goveralls

script:
  - go test -cover -v -covermode=count -coverprofile=coverage.out ./counter && $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - tip
